### ISSUE TITLE
Project 2 Proposal Peer Review

### ISSUE THREAD

**Issue by YitianQian777** [INFO-526-FA24/project-2-insight-decoders#1]
**The following is the peer review of the project proposal by [Epidata]. The team members that participated in this review are**
[Yitian Qian] - @[YitianQian777]
⁠[Rohit Surya AVB] - @[rozay_avb_dev]
⁠[Meghana Maringanti] - @[Meghana-Maringanti]
⁠⁠[Li Mi] - @[LiMi686]

**Describe the goal of the project.**
The goal of this project is to explore the gaming ecosystem using data visualizations.

**Describe the data used or collected.**
The dataset is from Kaggle, which contains 10000 records related to gaming. The key features include platform, genre, user rating, release year, region and development budget.

**Describe how the research question will be answered, e.g. what approaches / methods will be used.**
Temporal Trends: They will use time-series analysis to chart game releases and try to identify the peeks and trends. 
Platform Dynamics: They plan to find the correlations and analyze user ratings across platforms in order to understand their popularity and satisfaction. 
Genre Popularity: They will track genre trends over time to predict emerging or declining genres.
Geographical Trends: They will identify the specific regions that lead in game development and how the results change over time. 
Economic Analysis: They will examine the relationship between development budgets, user ratings and sales. 
Audience Targeting: They aim to explore the differences on game perception from different user groups. But they did not specify what method they are going to solve this question.

**Is there anything that is unclear from the proposal?**
They did not mention the potential methods that might be used in terms of research questions. 
They did not specify the candidate visualization graphs for each question. Some details they can add are:
For question1- which graph they will use to observe and analyze the trends. 
For question 3 - which methods they will use to understand the trend and how it can help to predict future trends
For question 5 - detail what techniques they will use to identify the correlation between investment and quality/popularity if any.

**Provide constructive feedback on how the team might be able to improve their project.**
They stated in the objective section that they would employ a data visualization package not covered in class, but they did not specify which package they were going to use and what question they were planning to use it for.

**What aspect of this project are you most interested in and would like to see highlighted in the presentation.**
For us the most compelling aspects of this project are temporal trends in game releases, platform dynamics, and genre popularity. I see that the Temporal trends aims to highlight the growth of the gaming industry, we are interested to see how and what visualization they will use to show this data. 
Platform dynamics provide insights into user preferences, revealing which platforms dominate and how they correlate with user satisfaction.We are interested to see if there is a particular platform and any particular game type that is the most popular across all regions and all age-groups. 
As we can see the project also explores geographical trends, showcasing the global contributions of various regions, and examines the relationship between development budgets and game success.

**Provide constructive feedback on any issues with file and/or code organization.**
In the proposal, they wrote that there are 1000 records, but in the dataset_summary.html file, they wrote that there are 10,000 records. So this is a confusing contradiction. In addition, they did not provide the link for the dataset, so we don’t know which one is the correct answer. They could embed the link for the dataset in the proposal file.

**Comment by hemabk** [comment]
Hi Epidata Team,

Thank you for your valuable feedback. Here’s a summary of the points you raised and how we have resolved them:

1) Dataset Size Discrepancy: You pointed out inconsistencies in the dataset size. We cross-checked and updated the proposal to reflect the correct dataset size of 4989 rows and 11 columns. We also provided a direct link to the dataset.

2) Visualization Package Specification: You noted that we didn’t specify which package we would use. We have now explicitly mentioned exploring gganimate, particularly for time-series data, and plotly, for interactive visualizations.

3) Clarity on Methods and Visualizations: For temporal trends, we will use line graphs; for genre popularity, stacked bar charts; and for economic analysis, correlation and regression analysis combined with outlier detection. These updates have been added to the proposal.

Thank you for helping us improve the clarity and quality of our project. Your insights were incredibly helpful!

Additionally, we appreciate that the team understood our project goals and showed interest in temporal trends, platform dynamics, and geographical trends. We will highlight these aspects and are equally eager to uncover and present these results.

Best regards,
Team Insight Decoders
