### ISSUE TITLE
Review from DataVizionaries

### ISSUE THREAD

**Issue by srikrish2812** [INFO-526-FA24/project-2-insight-decoders#4]
Topic: Gaming Trends Analysis

Strength: The gaming trends were explored thoroughly and the plots were easy to understand. The visualizations are plotted using a good color palette.

Weakness: Plots and text could be rearranged so that they don't overlap with each other.

**Comment by Rohith710** [comment]
Thank you for your valuable feedback ,we are making sure that we will address and consider your suggestion
