### ISSUE TITLE
Review from Insight Spark

### ISSUE THREAD

**Issue by ronymacwan** [INFO-526-FA24/project-2-insight-decoders#5]
Strength:
The analysis of gaming trends over the years is thorough and insightful. The use of a rolling average to predict future trends adds a strong analytical element.

Weakness:
Poster can benefit from a more efficient use of space. A more streamlined layout could help in presenting the information more clearly.

**Comment by Rohith710** [comment]
Thank you for your valuable feedback ,we are making sure that we will address and align our poster in a professional manner
