### ISSUE TITLE
Review by Visual Voyagers

### ISSUE THREAD

**Issue by bhaskar-237** [INFO-526-FA24/project-2-insight-decoders#6]
Strengths: Gaming trends are well captured with a variety of different plots

Weaknesses: Remove the redundant data from the the heat map(ideally the top half from the diagonal) and delete the labels on the x-axis as it is the same on the y-axis to increase data to ink ratio

**Comment by Rohith710** [comment]
Thank you for your valuable feedback ,we are making sure that we will address and remove the reductant data (which has multicollinearity) .
