### ISSUE TITLE
Review from team DataWaves

### ISSUE THREAD

**Issue by NavyasreeMadhu14** [INFO-526-FA24/project-2-insight-decoders#7]
Strength: The study presented numerous findings, supported by various plots to effectively showcase their results, which is highly appreciated.

Weakness: The poster's outlook could be improved by enhancing the arrangement of text and plots and utilizing space more effectively.

**Comment by Kaushik0802** [comment]
I appreciate your observation regarding the poster’s layout. To enhance its professional appearance, I will focus on reorganizing the arrangement of text and plots to create a more balanced and cohesive structure. Additionally, I will work on optimizing the use of space to ensure the content is presented in a clear, visually appealing, and impactful manner. Thank you
