### ISSUE TITLE
Review from team DreamJobs

### ISSUE THREAD

**Issue by Lucifer970901** [INFO-526-FA24/project-2-insight-decoders#8]
for the scattor plot with  try to change the range to 90 days so that we can see the variations.

**Comment by Naveenksaragadam** [comment]
Overall, the poster is well put together, and I appreciate how you went above and beyond the scope of the project by extrapolating the data. However, adding more context to the project would enhance its clarity. 

The references could be shortened, and the chart could be organized more effectively. It would be great to see a treemap view of gaming by platform. Additionally, ensure that the legends are well-organized and easily readable.
Good luck.

**Comment by Rohith710** [comment]
Thank you for your valuable feedback ,we are making sure that we will address and consider your suggestion
